In [ ]:
from datasets import load_dataset, concatenate_datasets


dataset_ood = load_dataset("project-oceania/planktonzilla_ood")
dataset_id = load_dataset("project-oceania/planktonzilla_only_plankton", split="test")

def set_unknown(batch):
    batch["label"] = [-1] * len(batch["label"])
    return batch
    
ds_ood = dataset_ood["train"].take(10000).map(set_unknown, batched=True, num_proc=4)

ds_test = concatenate_datasets([ds_ood, dataset_id])

/lustre/fswork/projects/rech/tec/uod68bo/planktonzilla/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [15]:
ds_ood = ds_ood.cast(dataset_id.features)

Casting the dataset: 100%|██████████| 10000/10000 [00:00<00:00, 94855.56 examples/s]

In [19]:
dataset_id.features

{'image': Image(mode=None, decode=True),

In [23]:
f =dataset_ood["train"].features

In [27]:
f["label"].names = ["ood"]

In [28]:
f

{'image': Image(mode=None, decode=True),
 'label': ClassLabel(names=['ood']),
 'dataset': Value('string')}

In [29]:
ds_ood = ds_ood.cast(f)

Casting the dataset: 100%|██████████| 10000/10000 [00:00<00:00, 109620.04 examples/s]

In [30]:
ds_test = concatenate_datasets([ds_ood, dataset_id])

ValueError: The features can't be aligned because the key label of features {'image': Image(mode=None, decode=True), 'label': ClassLabel(names=['animalia annelida', 'animalia annelida polychaeta', 'animalia annelida polychaeta phyllodocida', 'animalia annelida polychaeta phyllodocida tomopteridae', 'animalia annelida polychaeta terebellida acrocirridae swima', 'animalia annelida polychaeta terebellida flabelligeridae poeobius', 'animalia arthropoda', 'animalia arthropoda arachnida trombidiformes', 'animalia arthropoda arachnida trombidiformes halacaridae', 'animalia arthropoda branchiopoda anomopoda bosminidae bosmina', 'animalia arthropoda branchiopoda anomopoda daphniidae ceriodaphnia', 'animalia arthropoda branchiopoda anomopoda daphniidae daphnia', 'animalia arthropoda branchiopoda ctenopoda sididae diaphanosoma', 'animalia arthropoda branchiopoda ctenopoda sididae penilia', 'animalia arthropoda branchiopoda ctenopoda sididae penilia avirostris', 'animalia arthropoda branchiopoda haplopoda leptodoridae leptodora', 'animalia arthropoda branchiopoda onychopoda podonidae evadne', 'animalia arthropoda branchiopoda onychopoda podonidae podon', 'animalia arthropoda copepoda', 'animalia arthropoda copepoda calanoida', 'animalia arthropoda copepoda calanoida acartiidae', 'animalia arthropoda copepoda calanoida augaptilidae haloptilus', 'animalia arthropoda copepoda calanoida calanidae', 'animalia arthropoda copepoda calanoida candaciidae', 'animalia arthropoda copepoda calanoida centropagidae', 'animalia arthropoda copepoda calanoida centropagidae isias', 'animalia arthropoda copepoda calanoida diaptomidae eudiaptomus', 'animalia arthropoda copepoda calanoida eucalanidae', 'animalia arthropoda copepoda calanoida euchaetidae', 'animalia arthropoda copepoda calanoida euchaetidae euchaeta', 'animalia arthropoda copepoda calanoida heterorhabdidae', 'animalia arthropoda copepoda calanoida metridinidae pleuromamma abdominalis', 'animalia arthropoda copepoda calanoida metrinidae', 'animalia arthropoda copepoda calanoida paracalanidae calocalanus', 'animalia arthropoda copepoda calanoida paracalanidae calocalanus pavo', 'animalia arthropoda copepoda calanoida pontellidae', 'animalia arthropoda copepoda calanoida rhincalanidae', 'animalia arthropoda copepoda calanoida temoridae', 'animalia arthropoda copepoda cyclopoida', 'animalia arthropoda copepoda cyclopoida corycaeidae', 'animalia arthropoda copepoda cyclopoida cyclopidae cyclops', 'animalia arthropoda copepoda cyclopoida oithonidae', 'animalia arthropoda copepoda cyclopoida oncaeidae', 'animalia arthropoda copepoda cyclopoida oncaeidae oncaea', 'animalia arthropoda copepoda cyclopoida sapphirinidae', 'animalia arthropoda copepoda cyclopoida sapphirinidae copilia', 'animalia arthropoda copepoda harpacticoida', 'animalia arthropoda copepoda harpacticoida tachidiidae euterpina', 'animalia arthropoda diplopoda siphonophorida siphonophoridae siphonophora', 'animalia arthropoda hexapoda ephemeroptera ephemeridae ephemera', 'animalia arthropoda insecta diptera chaoboridae chaoborus', 'animalia arthropoda malacostraca', 'animalia arthropoda malacostraca amphipoda', 'animalia arthropoda malacostraca cumacea', 'animalia arthropoda malacostraca decapoda', 'animalia arthropoda malacostraca decapoda galatheidae', 'animalia arthropoda malacostraca decapoda luciferidae', 'animalia arthropoda malacostraca decapoda penaeidae', 'animalia arthropoda malacostraca decapoda porcellanidae', 'animalia arthropoda malacostraca decapoda sergestidae', 'animalia arthropoda malacostraca euphausiacea', 'animalia arthropoda malacostraca isopoda cirolanidae eurydice', 'animalia arthropoda malacostraca mysida', 'animalia arthropoda malacostraca mysida mysidae mysis', 'animalia arthropoda malacostraca stomatopoda', 'animalia arthropoda malacostraca stomatopoda nannosquillidae', 'animalia arthropoda ostracoda', 'animalia arthropoda thecostraca', 'animalia arthropoda thecostraca sessilia', 'animalia bryozoa', 'animalia chaetognatha', 'animalia chordata', 'animalia chordata appendicularia', 'animalia chordata appendicularia copelata fritillariidae', 'animalia chordata appendicularia copelata oikopleuridae', 'animalia chordata teleostei clupeiformes', 'animalia chordata thaliacea', 'animalia chordata thaliacea doliolida', 'animalia chordata thaliacea pyrosomatida', 'animalia chordata thaliacea salpida', 'animalia chordata thaliacea salpida salpidae', 'animalia cnidaria', 'animalia cnidaria hexacorallia actiniaria', 'animalia cnidaria hexacorallia scleractinia caryophylliidae multiplexcyathus', 'animalia cnidaria hydrozoa', 'animalia cnidaria hydrozoa anthoathecata hydridae hydra', 'animalia cnidaria hydrozoa leptothecata campanulariidae obelia', 'animalia cnidaria hydrozoa limnomedusae geryoniidae liriope', 'animalia cnidaria hydrozoa narcomedusae', 'animalia cnidaria hydrozoa narcomedusae solmundaeginidae solmundella bitentaculata', 'animalia cnidaria hydrozoa siphonophorae', 'animalia cnidaria hydrozoa siphonophorae abylidae abylopsis', 'animalia cnidaria hydrozoa siphonophorae abylidae abylopsis tetragona', 'animalia cnidaria hydrozoa siphonophorae abylidae bassia bassensis', 'animalia cnidaria hydrozoa siphonophorae diphyidae', 'animalia cnidaria hydrozoa siphonophorae hippopodiidae', 'animalia cnidaria hydrozoa trachymedusae', 'animalia cnidaria hydrozoa trachymedusae halicreatidae botrynema', 'animalia cnidaria hydrozoa trachymedusae rhopalonematidae', 'animalia cnidaria hydrozoa trachymedusae rhopalonematidae aglaura hemistoma', 'animalia cnidaria hydrozoa trachymedusae rhopalonematidae rhopalonema velatum', 'animalia cnidaria scyphozoa', 'animalia echinodermata', 'animalia echinodermata asteroidea paxillosida luidiidae', 'animalia echinodermata crinoidea', 'animalia echinodermata echinoidea', 'animalia echinodermata ophiuroidea', 'animalia hemichordata enteropneusta', 'animalia mollusca', 'animalia mollusca bivalvia', 'animalia mollusca bivalvia pteriida inoceramidae cladoceramus', 'animalia mollusca gastropoda', 'animalia mollusca gastropoda littorinimorpha atlantidae', 'animalia mollusca gastropoda pteropoda', 'animalia mollusca gastropoda pteropoda cavoliniidae', 'animalia mollusca gastropoda pteropoda cavoliniidae cavolinia inflexa', 'animalia mollusca gastropoda pteropoda cliidae clio pyramidata', 'animalia mollusca gastropoda pteropoda creseidae creseis acicula', 'animalia mollusca gastropoda pteropoda cymbuliidae cymbulia peroni', 'animalia mollusca gastropoda pteropoda limacinidae', 'animalia mollusca gastropoda pylopulmonata pyramidellidae microstellaria', 'animalia phoronida', 'animalia rotifera', 'animalia rotifera eurotatoria flosculariaceae conochilidae conochilus', 'animalia rotifera eurotatoria ploima asplanchnidae asplanchna', 'animalia rotifera eurotatoria ploima brachionidae brachionus', 'animalia rotifera eurotatoria ploima brachionidae kellicottia', 'animalia rotifera eurotatoria ploima brachionidae keratella cochlearis', 'animalia rotifera eurotatoria ploima brachionidae keratella quadrata', 'animalia rotifera eurotatoria ploima synchaetidae polyarthra', 'animalia rotifera eurotatoria ploima synchaetidae synchaeta', 'animalia rotifera eurotatoria ploima trichocercidae trichocerca', 'bacteria cyanobacteria', 'bacteria cyanobacteria cyanophyceae', 'bacteria cyanobacteria cyanophyceae gomontiellales gomontiellaceae katagnymene spiralis', 'bacteria cyanobacteria cyanophyceae nostocales aphanizomenonaceae aphanizomenon', 'bacteria cyanobacteria cyanophyceae nostocales rivulariaceae richelia', 'bacteria cyanobacteria cyanophyceae oscillatoriales microcoleaceae trichodesmium', 'chromista', 'chromista cercozoa thecofilosea', 'chromista cercozoa thecofilosea phaeocystida aulacanthidae', 'chromista cercozoa thecofilosea phaeodendrida coelodendridae', 'chromista cercozoa thecofilosea phaeosphaerida aulosphaeridae', 'chromista ciliophora', 'chromista ciliophora heterotrichea heterotrichida blepharismidae blepharisma americanum', 'chromista ciliophora heterotrichea heterotrichida spirostomidae spirostomum ambiguum', 'chromista ciliophora heterotrichea heterotrichida stentoridae stentor coeruleus', 'chromista ciliophora litostomatea cyclotrichiida mesodiniidae mesodinium', 'chromista ciliophora litostomatea haptorida didiniidae didinium', 'chromista ciliophora litostomatea haptorida didiniidae didinium nasutum', 'chromista ciliophora litostomatea haptorida tracheliidae dileptus', 'chromista ciliophora litostomatea haptorida tracheliidae paradileptus', 'chromista ciliophora oligohymenophorea peniculida parameciidae paramecium bursaria', 'chromista ciliophora oligohymenophorea pleuronematida pleuronematidae pleuronema', 'chromista ciliophora oligotrichea choreotrichida', 'chromista ciliophora oligotrichea choreotrichida codonellidae codonaria', 'chromista ciliophora oligotrichea choreotrichida codonellidae poroecus', 'chromista ciliophora oligotrichea choreotrichida codonellopsidae codonellopsis morchella', 'chromista ciliophora oligotrichea choreotrichida dictyocystidae dictyocysta', 'chromista ciliophora oligotrichea choreotrichida epiplocylididae epiplocylis', 'chromista ciliophora oligotrichea choreotrichida eutintinnidae eutintinnus', 'chromista ciliophora oligotrichea choreotrichida leegaardiellidae leegaardiella ovalis', 'chromista ciliophora oligotrichea choreotrichida metacylididae metacylis', 'chromista ciliophora oligotrichea choreotrichida rhabdonellidae rhabdonella', 'chromista ciliophora oligotrichea choreotrichida strobilidiidae strobilidium', 'chromista ciliophora oligotrichea choreotrichida tintinnidae amphorides', 'chromista ciliophora oligotrichea choreotrichida tintinnidae salpingella', 'chromista ciliophora oligotrichea choreotrichida tintinnidae steenstrupiella', 'chromista ciliophora oligotrichea choreotrichida undellidae', 'chromista ciliophora oligotrichea choreotrichida xystonellidae', 'chromista ciliophora oligotrichea oligotrichida strombidiidae strombidium', 'chromista ciliophora oligotrichea oligotrichida strombidiidae strombidium capitatum', 'chromista ciliophora oligotrichea oligotrichida strombidiidae strombidium conicum', 'chromista ciliophora oligotrichea oligotrichida strombidiidae strombidium inclinatum', 'chromista ciliophora oligotrichea oligotrichida strombidiidae strombidium oculatum', 'chromista ciliophora oligotrichea oligotrichida strombidiidae strombidium wulffi', 'chromista ciliophora oligotrichea oligotrichida tontoniidae laboea strobila', 'chromista ciliophora oligotrichea oligotrichida tontoniidae tontonia appendiculariformis', 'chromista ciliophora oligotrichea oligotrichida tontoniidae tontonia gracillima', 'chromista ciliophora prostomatea prorodontida colepidae tiarina', 'chromista ciliophora prostomatea prorodontida colepidae tiarina fusus', 'chromista ciliophora spirotrichea euplotida euplotidae euplotes', 'chromista ciliophora spirotrichea euplotida euplotidae euplotes eurystomus', 'chromista ciliophora spirotrichea tintinnida', 'chromista cryptophyta cryptophyceae', 'chromista foraminifera', 'chromista foraminifera globothalamea rotaliida globigerinidae', 'chromista haptophyta coccolithophyceae coccolithales calcidiscaceae umbilicosphaera sibogae', 'chromista haptophyta coccolithophyceae isochrysidales noelaerhabdaceae gephyrocapsa huxleyi', 'chromista haptophyta coccolithophyceae phaeocystales phaeocystaceae phaeocystis', 'chromista haptophyta coccolithophyceae phaeocystales phaeocystaceae phaeocystis jahnii', 'chromista haptophyta coccolithophyceae prymnesiales chrysochromulinaceae chrysochromulina', 'chromista haptophyta coccolithophyceae prymnesiales chrysochromulinaceae chrysochromulina lanceolata', 'chromista haptophyta coccolithophyceae prymnesiales chrysochromulinaceae chrysochromulina parkeae', 'chromista haptophyta coccolithophyceae syracosphaerales calciosoleniaceae calciosolenia brasiliensis', 'chromista haptophyta coccolithophyceae syracosphaerales rhabdosphaeraceae discosphaera tubifera', 'chromista haptophyta coccolithophyceae syracosphaerales rhabdosphaeraceae rhabdosphaera clavigera', 'chromista haptophyta coccolithophyceae syracosphaerales syracosphaeraceae calciopappus caudatus', 'chromista haptophyta coccolithophyceae syracosphaerales syracosphaeraceae ophiaster', 'chromista haptophyta coccolithophyceae syracosphaerales syracosphaeraceae syracosphaera pulchra', 'chromista haptophyta coccolithophyceae zygodiscales pontosphaeraceae scyphosphaera apsteinii', 'chromista heterokontophyta bacillariophyceae', 'chromista heterokontophyta bacillariophyceae asterolamprales', 'chromista heterokontophyta bacillariophyceae asterolamprales asterolampraceae asteromphalus', 'chromista heterokontophyta bacillariophyceae asterolamprales asterolampraceae asteromphalus sarcophagus', 'chromista heterokontophyta bacillariophyceae bacillariales bacillariaceae bacillaria', 'chromista heterokontophyta bacillariophyceae bacillariales bacillariaceae cylindrotheca', 'chromista heterokontophyta bacillariophyceae bacillariales bacillariaceae cylindrotheca closterium', 'chromista heterokontophyta bacillariophyceae bacillariales bacillariaceae fragilariopsis', 'chromista heterokontophyta bacillariophyceae bacillariales bacillariaceae nitzschia', 'chromista heterokontophyta bacillariophyceae bacillariales bacillariaceae pseudo-nitzschia', 'chromista heterokontophyta bacillariophyceae bacillariales bacillariaceae pseudo-nitzschia chain', 'chromista heterokontophyta bacillariophyceae biddulphiales biddulphiaceae biddulphia', 'chromista heterokontophyta bacillariophyceae biddulphiales biddulphiaceae neobrightwellia alternans', 'chromista heterokontophyta bacillariophyceae centrales', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae bacteriastrum', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae chaetoceros', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae chaetoceros anastomonsans', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae chaetoceros danicus', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae chaetoceros decipiens', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae chaetoceros didymus', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae chaetoceros diversus', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae chaetoceros peruvianus', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae chaetoceros socialis', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae chaetoceros tortissimus', 'chromista heterokontophyta bacillariophyceae corethrales corethraceae corethron', 'chromista heterokontophyta bacillariophyceae coscinodiscales coscinodiscaceae', 'chromista heterokontophyta bacillariophyceae coscinodiscales coscinodiscaceae coscinodiscus', 'chromista heterokontophyta bacillariophyceae fragilariales fragilariaceae asterionella', 'chromista heterokontophyta bacillariophyceae fragilariales fragilariaceae asterionellopsis', 'chromista heterokontophyta bacillariophyceae fragilariales fragilariaceae asterionellopsis glacialis', 'chromista heterokontophyta bacillariophyceae fragilariales fragilariaceae ctenophora', 'chromista heterokontophyta bacillariophyceae fragilariales fragilariaceae diatoma', 'chromista heterokontophyta bacillariophyceae fragilariales fragilariaceae diatoma tenuis', 'chromista heterokontophyta bacillariophyceae fragilariales fragilariaceae fragilaria', 'chromista heterokontophyta bacillariophyceae hemiaulales hemiaulaceae cerataulina', 'chromista heterokontophyta bacillariophyceae hemiaulales hemiaulaceae cerataulina pelagica', 'chromista heterokontophyta bacillariophyceae hemiaulales hemiaulaceae climacodium', 'chromista heterokontophyta bacillariophyceae hemiaulales hemiaulaceae climacodium crocosphaera', 'chromista heterokontophyta bacillariophyceae hemiaulales hemiaulaceae eucampia', 'chromista heterokontophyta bacillariophyceae hemiaulales hemiaulaceae eucampia cornuta', 'chromista heterokontophyta bacillariophyceae hemiaulales hemiaulaceae hemiaulus', 'chromista heterokontophyta bacillariophyceae leptocylindrales leptocylindraceae leptocylindrus', 'chromista heterokontophyta bacillariophyceae leptocylindrales leptocylindraceae leptocylindrus mediterraneus', 'chromista heterokontophyta bacillariophyceae leptocylindrales leptocylindraceae tenuicylindrus belgicus', 'chromista heterokontophyta bacillariophyceae licmophorales licmophoraceae licmophora', 'chromista heterokontophyta bacillariophyceae lithodesmiales lithodesmiaceae ditylum', 'chromista heterokontophyta bacillariophyceae lithodesmiales lithodesmiaceae helicotheca tamesis', 'chromista heterokontophyta bacillariophyceae lithodesmiales lithodesmiaceae lithodesmium variabile', 'chromista heterokontophyta bacillariophyceae melosirales melosiraceae', 'chromista heterokontophyta bacillariophyceae melosirales stephanopyxidaceae stephanopyxis', 'chromista heterokontophyta bacillariophyceae naviculales naviculaceae haslea silbo', 'chromista heterokontophyta bacillariophyceae naviculales plagiotropidaceae plagiotropis', 'chromista heterokontophyta bacillariophyceae naviculales pleurosigmataceae', 'chromista heterokontophyta bacillariophyceae naviculales pleurosigmataceae pleurosigma', 'chromista heterokontophyta bacillariophyceae paraliales paraliaceae paralia', 'chromista heterokontophyta bacillariophyceae pennales', 'chromista heterokontophyta bacillariophyceae rhaponeidales rhaphoneidaceae delphineis', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae dactyliosolen', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae dactyliosolen blavyanus', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae dactyliosolen fragilissimus', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae guinardia', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae guinardia delicatula', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae guinardia flaccida', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae guinardia striata', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae pseudosolenia calcar-avis', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae rhizosolenia', 'chromista heterokontophyta bacillariophyceae thalassionematales', 'chromista heterokontophyta bacillariophyceae thalassionematales thalassionemataceae lioloma pacificum', 'chromista heterokontophyta bacillariophyceae thalassionematales thalassionemataceae thalassionema', 'chromista heterokontophyta bacillariophyceae thalassiosirales lauderiaceae lauderia', 'chromista heterokontophyta bacillariophyceae thalassiosirales lauderiaceae lauderia annulata', 'chromista heterokontophyta bacillariophyceae thalassiosirales skeletonemaceae skeletonema', 'chromista heterokontophyta bacillariophyceae thalassiosirales skeletonemaceae skeletonema menzelii', 'chromista heterokontophyta bacillariophyceae thalassiosirales thalassiosiraceae planktoniella sol', 'chromista heterokontophyta bacillariophyceae thalassiosirales thalassiosiraceae thalassiosira', 'chromista heterokontophyta bacillariophyceae thalassiosirales thalassiosiraceae thalassiosira gravida', 'chromista heterokontophyta bacillariophyceae triceratiales triceratiaceae odontella', 'chromista heterokontophyta bacillariophyceae triceratiales triceratiaceae trieres mobiliensis', 'chromista myzozoa dinophyceae', 'chromista myzozoa dinophyceae amphidiniales amphidiniaceae amphidinium', 'chromista myzozoa dinophyceae dinophyceae amphidomataceae azadinium caudatum', 'chromista myzozoa dinophyc

In [7]:
from datasets import concatenate_datasets

In [ ]:
dataset_ood["train"].take(10000)

DatasetDict({
    train: Dataset({
        features: ['image', 'label', 'dataset'],
        num_rows: 6701849
    })
})

In [9]:
def set_unknown(batch):
    batch["label"] = [-1] * len(batch["label"])
    return batch
    
ds_ood = dataset_ood["train"].take(10000).map(set_unknown, batched=True, num_proc=4)

Map (num_proc=4): 100%|██████████| 10000/10000 [00:03<00:00, 3161.44 examples/s]

In [13]:
ds_ood.features

{'image': Image(mode=None, decode=True),
 'label': ClassLabel(names=['Bubbles', 'Eggs', 'Fibers_etc', 'Fish_eggs', 'Insecta', 'LClass_32.1Adult_Fish', 'LClass_33.Air_bubble', 'LClass_Barnacle', 'LClass_Benthic_Algae', 'LClass_Cnidaria', 'LClass_Detritus', 'LClass_Detritus_dot', 'LClass_Detritus_stickers', 'LClass_Doubts', 'LClass_Doutbs', 'LClass_Egg', 'LClass_Fish_larvae', 'LClass_Foraminifera', 'LClass_Gastropoda', 'LClass_Hydracarina', 'LClass_Organism_parts_general', 'LClass_Pa.35.Marine_snow', 'LClass_Pa.35.Marine_snow_aggregate_large', 'LClass_Pa.35.Marine_snow_aggregate_medium', 'LClass_Pa.35.Marine_snow_aggregate_small', 'LClass_Pa.35.Marine_snow_com_large', 'LClass_Pa.35.Marine_snow_com_medium', 'LClass_Pa.35.Marine_snow_com_small', 'LClass_Pa.35.Marine_snow_stick', 'LClass_Pa.36.Fecal_pellets', 'LClass_Pa.36.Fecal_pellets_New', 'LClass_Pa.39.Mineral', 'LClass_Pa.Mineral', 'LClass_Pa.Other_exuviae', 'LClass_Pluteus', 'LClass_Unfocussed', 'LClass_Unkown', 'LClass_benthic_algae', 'LClass_chaetognatha', 'LClass_crinoidea', 'LClass_doubt', 'LClass_doubts', 'LClass_egg', 'LClass_eggs', 'LClass_fish_lavae', 'LClass_larvacea', 'LClass_multiple_organisms', 'LClass_organism_border', 'LClass_partCrustaceo', 'LClass_pluteos', 'LClass_pteropod', 'LClass_shell', 'LClass_unknown', 'LRaw', 'artefact', 'bad', 'badfocus', 'ball_bearing_like', 'bead', 'bubble', 'contrasted_blob', 'crumple sphere', 'crystal', 'dark', 'darkrods', 'darksphere', 'detritus', 'dinophyceae_shape', 'dirt', 'feces', 'fiber', 'fiber_detritus', 'fiber_plastic', 'filament', 'fish', 'gelatinous', 'light', 'light_detritus', 'lightrods', 'lightsphere', 'medium_detritus', 'mix', 'mix_elongated', 'other<living', 'other_egg', 'other_interaction', 'other_living', 'other_plastic', 'pollen', 'reflection', 'seaweed', 'streak', 't004', 't011', 'transparent_u', 'unknown', 'vertical line']),
 'dataset': Value('string')}

In [6]:
dataset_id = load_dataset("project-oceania/planktonzilla_only_plankton", split="test")

In [14]:
ds_test = concatenate_datasets([ds_ood, dataset_id])

ValueError: The features can't be aligned because the key label of features {'image': Image(mode=None, decode=True), 'label': ClassLabel(names=['animalia annelida', 'animalia annelida polychaeta', 'animalia annelida polychaeta phyllodocida', 'animalia annelida polychaeta phyllodocida tomopteridae', 'animalia annelida polychaeta terebellida acrocirridae swima', 'animalia annelida polychaeta terebellida flabelligeridae poeobius', 'animalia arthropoda', 'animalia arthropoda arachnida trombidiformes', 'animalia arthropoda arachnida trombidiformes halacaridae', 'animalia arthropoda branchiopoda anomopoda bosminidae bosmina', 'animalia arthropoda branchiopoda anomopoda daphniidae ceriodaphnia', 'animalia arthropoda branchiopoda anomopoda daphniidae daphnia', 'animalia arthropoda branchiopoda ctenopoda sididae diaphanosoma', 'animalia arthropoda branchiopoda ctenopoda sididae penilia', 'animalia arthropoda branchiopoda ctenopoda sididae penilia avirostris', 'animalia arthropoda branchiopoda haplopoda leptodoridae leptodora', 'animalia arthropoda branchiopoda onychopoda podonidae evadne', 'animalia arthropoda branchiopoda onychopoda podonidae podon', 'animalia arthropoda copepoda', 'animalia arthropoda copepoda calanoida', 'animalia arthropoda copepoda calanoida acartiidae', 'animalia arthropoda copepoda calanoida augaptilidae haloptilus', 'animalia arthropoda copepoda calanoida calanidae', 'animalia arthropoda copepoda calanoida candaciidae', 'animalia arthropoda copepoda calanoida centropagidae', 'animalia arthropoda copepoda calanoida centropagidae isias', 'animalia arthropoda copepoda calanoida diaptomidae eudiaptomus', 'animalia arthropoda copepoda calanoida eucalanidae', 'animalia arthropoda copepoda calanoida euchaetidae', 'animalia arthropoda copepoda calanoida euchaetidae euchaeta', 'animalia arthropoda copepoda calanoida heterorhabdidae', 'animalia arthropoda copepoda calanoida metridinidae pleuromamma abdominalis', 'animalia arthropoda copepoda calanoida metrinidae', 'animalia arthropoda copepoda calanoida paracalanidae calocalanus', 'animalia arthropoda copepoda calanoida paracalanidae calocalanus pavo', 'animalia arthropoda copepoda calanoida pontellidae', 'animalia arthropoda copepoda calanoida rhincalanidae', 'animalia arthropoda copepoda calanoida temoridae', 'animalia arthropoda copepoda cyclopoida', 'animalia arthropoda copepoda cyclopoida corycaeidae', 'animalia arthropoda copepoda cyclopoida cyclopidae cyclops', 'animalia arthropoda copepoda cyclopoida oithonidae', 'animalia arthropoda copepoda cyclopoida oncaeidae', 'animalia arthropoda copepoda cyclopoida oncaeidae oncaea', 'animalia arthropoda copepoda cyclopoida sapphirinidae', 'animalia arthropoda copepoda cyclopoida sapphirinidae copilia', 'animalia arthropoda copepoda harpacticoida', 'animalia arthropoda copepoda harpacticoida tachidiidae euterpina', 'animalia arthropoda diplopoda siphonophorida siphonophoridae siphonophora', 'animalia arthropoda hexapoda ephemeroptera ephemeridae ephemera', 'animalia arthropoda insecta diptera chaoboridae chaoborus', 'animalia arthropoda malacostraca', 'animalia arthropoda malacostraca amphipoda', 'animalia arthropoda malacostraca cumacea', 'animalia arthropoda malacostraca decapoda', 'animalia arthropoda malacostraca decapoda galatheidae', 'animalia arthropoda malacostraca decapoda luciferidae', 'animalia arthropoda malacostraca decapoda penaeidae', 'animalia arthropoda malacostraca decapoda porcellanidae', 'animalia arthropoda malacostraca decapoda sergestidae', 'animalia arthropoda malacostraca euphausiacea', 'animalia arthropoda malacostraca isopoda cirolanidae eurydice', 'animalia arthropoda malacostraca mysida', 'animalia arthropoda malacostraca mysida mysidae mysis', 'animalia arthropoda malacostraca stomatopoda', 'animalia arthropoda malacostraca stomatopoda nannosquillidae', 'animalia arthropoda ostracoda', 'animalia arthropoda thecostraca', 'animalia arthropoda thecostraca sessilia', 'animalia bryozoa', 'animalia chaetognatha', 'animalia chordata', 'animalia chordata appendicularia', 'animalia chordata appendicularia copelata fritillariidae', 'animalia chordata appendicularia copelata oikopleuridae', 'animalia chordata teleostei clupeiformes', 'animalia chordata thaliacea', 'animalia chordata thaliacea doliolida', 'animalia chordata thaliacea pyrosomatida', 'animalia chordata thaliacea salpida', 'animalia chordata thaliacea salpida salpidae', 'animalia cnidaria', 'animalia cnidaria hexacorallia actiniaria', 'animalia cnidaria hexacorallia scleractinia caryophylliidae multiplexcyathus', 'animalia cnidaria hydrozoa', 'animalia cnidaria hydrozoa anthoathecata hydridae hydra', 'animalia cnidaria hydrozoa leptothecata campanulariidae obelia', 'animalia cnidaria hydrozoa limnomedusae geryoniidae liriope', 'animalia cnidaria hydrozoa narcomedusae', 'animalia cnidaria hydrozoa narcomedusae solmundaeginidae solmundella bitentaculata', 'animalia cnidaria hydrozoa siphonophorae', 'animalia cnidaria hydrozoa siphonophorae abylidae abylopsis', 'animalia cnidaria hydrozoa siphonophorae abylidae abylopsis tetragona', 'animalia cnidaria hydrozoa siphonophorae abylidae bassia bassensis', 'animalia cnidaria hydrozoa siphonophorae diphyidae', 'animalia cnidaria hydrozoa siphonophorae hippopodiidae', 'animalia cnidaria hydrozoa trachymedusae', 'animalia cnidaria hydrozoa trachymedusae halicreatidae botrynema', 'animalia cnidaria hydrozoa trachymedusae rhopalonematidae', 'animalia cnidaria hydrozoa trachymedusae rhopalonematidae aglaura hemistoma', 'animalia cnidaria hydrozoa trachymedusae rhopalonematidae rhopalonema velatum', 'animalia cnidaria scyphozoa', 'animalia echinodermata', 'animalia echinodermata asteroidea paxillosida luidiidae', 'animalia echinodermata crinoidea', 'animalia echinodermata echinoidea', 'animalia echinodermata ophiuroidea', 'animalia hemichordata enteropneusta', 'animalia mollusca', 'animalia mollusca bivalvia', 'animalia mollusca bivalvia pteriida inoceramidae cladoceramus', 'animalia mollusca gastropoda', 'animalia mollusca gastropoda littorinimorpha atlantidae', 'animalia mollusca gastropoda pteropoda', 'animalia mollusca gastropoda pteropoda cavoliniidae', 'animalia mollusca gastropoda pteropoda cavoliniidae cavolinia inflexa', 'animalia mollusca gastropoda pteropoda cliidae clio pyramidata', 'animalia mollusca gastropoda pteropoda creseidae creseis acicula', 'animalia mollusca gastropoda pteropoda cymbuliidae cymbulia peroni', 'animalia mollusca gastropoda pteropoda limacinidae', 'animalia mollusca gastropoda pylopulmonata pyramidellidae microstellaria', 'animalia phoronida', 'animalia rotifera', 'animalia rotifera eurotatoria flosculariaceae conochilidae conochilus', 'animalia rotifera eurotatoria ploima asplanchnidae asplanchna', 'animalia rotifera eurotatoria ploima brachionidae brachionus', 'animalia rotifera eurotatoria ploima brachionidae kellicottia', 'animalia rotifera eurotatoria ploima brachionidae keratella cochlearis', 'animalia rotifera eurotatoria ploima brachionidae keratella quadrata', 'animalia rotifera eurotatoria ploima synchaetidae polyarthra', 'animalia rotifera eurotatoria ploima synchaetidae synchaeta', 'animalia rotifera eurotatoria ploima trichocercidae trichocerca', 'bacteria cyanobacteria', 'bacteria cyanobacteria cyanophyceae', 'bacteria cyanobacteria cyanophyceae gomontiellales gomontiellaceae katagnymene spiralis', 'bacteria cyanobacteria cyanophyceae nostocales aphanizomenonaceae aphanizomenon', 'bacteria cyanobacteria cyanophyceae nostocales rivulariaceae richelia', 'bacteria cyanobacteria cyanophyceae oscillatoriales microcoleaceae trichodesmium', 'chromista', 'chromista cercozoa thecofilosea', 'chromista cercozoa thecofilosea phaeocystida aulacanthidae', 'chromista cercozoa thecofilosea phaeodendrida coelodendridae', 'chromista cercozoa thecofilosea phaeosphaerida aulosphaeridae', 'chromista ciliophora', 'chromista ciliophora heterotrichea heterotrichida blepharismidae blepharisma americanum', 'chromista ciliophora heterotrichea heterotrichida spirostomidae spirostomum ambiguum', 'chromista ciliophora heterotrichea heterotrichida stentoridae stentor coeruleus', 'chromista ciliophora litostomatea cyclotrichiida mesodiniidae mesodinium', 'chromista ciliophora litostomatea haptorida didiniidae didinium', 'chromista ciliophora litostomatea haptorida didiniidae didinium nasutum', 'chromista ciliophora litostomatea haptorida tracheliidae dileptus', 'chromista ciliophora litostomatea haptorida tracheliidae paradileptus', 'chromista ciliophora oligohymenophorea peniculida parameciidae paramecium bursaria', 'chromista ciliophora oligohymenophorea pleuronematida pleuronematidae pleuronema', 'chromista ciliophora oligotrichea choreotrichida', 'chromista ciliophora oligotrichea choreotrichida codonellidae codonaria', 'chromista ciliophora oligotrichea choreotrichida codonellidae poroecus', 'chromista ciliophora oligotrichea choreotrichida codonellopsidae codonellopsis morchella', 'chromista ciliophora oligotrichea choreotrichida dictyocystidae dictyocysta', 'chromista ciliophora oligotrichea choreotrichida epiplocylididae epiplocylis', 'chromista ciliophora oligotrichea choreotrichida eutintinnidae eutintinnus', 'chromista ciliophora oligotrichea choreotrichida leegaardiellidae leegaardiella ovalis', 'chromista ciliophora oligotrichea choreotrichida metacylididae metacylis', 'chromista ciliophora oligotrichea choreotrichida rhabdonellidae rhabdonella', 'chromista ciliophora oligotrichea choreotrichida strobilidiidae strobilidium', 'chromista ciliophora oligotrichea choreotrichida tintinnidae amphorides', 'chromista ciliophora oligotrichea choreotrichida tintinnidae salpingella', 'chromista ciliophora oligotrichea choreotrichida tintinnidae steenstrupiella', 'chromista ciliophora oligotrichea choreotrichida undellidae', 'chromista ciliophora oligotrichea choreotrichida xystonellidae', 'chromista ciliophora oligotrichea oligotrichida strombidiidae strombidium', 'chromista ciliophora oligotrichea oligotrichida strombidiidae strombidium capitatum', 'chromista ciliophora oligotrichea oligotrichida strombidiidae strombidium conicum', 'chromista ciliophora oligotrichea oligotrichida strombidiidae strombidium inclinatum', 'chromista ciliophora oligotrichea oligotrichida strombidiidae strombidium oculatum', 'chromista ciliophora oligotrichea oligotrichida strombidiidae strombidium wulffi', 'chromista ciliophora oligotrichea oligotrichida tontoniidae laboea strobila', 'chromista ciliophora oligotrichea oligotrichida tontoniidae tontonia appendiculariformis', 'chromista ciliophora oligotrichea oligotrichida tontoniidae tontonia gracillima', 'chromista ciliophora prostomatea prorodontida colepidae tiarina', 'chromista ciliophora prostomatea prorodontida colepidae tiarina fusus', 'chromista ciliophora spirotrichea euplotida euplotidae euplotes', 'chromista ciliophora spirotrichea euplotida euplotidae euplotes eurystomus', 'chromista ciliophora spirotrichea tintinnida', 'chromista cryptophyta cryptophyceae', 'chromista foraminifera', 'chromista foraminifera globothalamea rotaliida globigerinidae', 'chromista haptophyta coccolithophyceae coccolithales calcidiscaceae umbilicosphaera sibogae', 'chromista haptophyta coccolithophyceae isochrysidales noelaerhabdaceae gephyrocapsa huxleyi', 'chromista haptophyta coccolithophyceae phaeocystales phaeocystaceae phaeocystis', 'chromista haptophyta coccolithophyceae phaeocystales phaeocystaceae phaeocystis jahnii', 'chromista haptophyta coccolithophyceae prymnesiales chrysochromulinaceae chrysochromulina', 'chromista haptophyta coccolithophyceae prymnesiales chrysochromulinaceae chrysochromulina lanceolata', 'chromista haptophyta coccolithophyceae prymnesiales chrysochromulinaceae chrysochromulina parkeae', 'chromista haptophyta coccolithophyceae syracosphaerales calciosoleniaceae calciosolenia brasiliensis', 'chromista haptophyta coccolithophyceae syracosphaerales rhabdosphaeraceae discosphaera tubifera', 'chromista haptophyta coccolithophyceae syracosphaerales rhabdosphaeraceae rhabdosphaera clavigera', 'chromista haptophyta coccolithophyceae syracosphaerales syracosphaeraceae calciopappus caudatus', 'chromista haptophyta coccolithophyceae syracosphaerales syracosphaeraceae ophiaster', 'chromista haptophyta coccolithophyceae syracosphaerales syracosphaeraceae syracosphaera pulchra', 'chromista haptophyta coccolithophyceae zygodiscales pontosphaeraceae scyphosphaera apsteinii', 'chromista heterokontophyta bacillariophyceae', 'chromista heterokontophyta bacillariophyceae asterolamprales', 'chromista heterokontophyta bacillariophyceae asterolamprales asterolampraceae asteromphalus', 'chromista heterokontophyta bacillariophyceae asterolamprales asterolampraceae asteromphalus sarcophagus', 'chromista heterokontophyta bacillariophyceae bacillariales bacillariaceae bacillaria', 'chromista heterokontophyta bacillariophyceae bacillariales bacillariaceae cylindrotheca', 'chromista heterokontophyta bacillariophyceae bacillariales bacillariaceae cylindrotheca closterium', 'chromista heterokontophyta bacillariophyceae bacillariales bacillariaceae fragilariopsis', 'chromista heterokontophyta bacillariophyceae bacillariales bacillariaceae nitzschia', 'chromista heterokontophyta bacillariophyceae bacillariales bacillariaceae pseudo-nitzschia', 'chromista heterokontophyta bacillariophyceae bacillariales bacillariaceae pseudo-nitzschia chain', 'chromista heterokontophyta bacillariophyceae biddulphiales biddulphiaceae biddulphia', 'chromista heterokontophyta bacillariophyceae biddulphiales biddulphiaceae neobrightwellia alternans', 'chromista heterokontophyta bacillariophyceae centrales', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae bacteriastrum', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae chaetoceros', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae chaetoceros anastomonsans', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae chaetoceros danicus', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae chaetoceros decipiens', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae chaetoceros didymus', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae chaetoceros diversus', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae chaetoceros peruvianus', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae chaetoceros socialis', 'chromista heterokontophyta bacillariophyceae chaetocerotanae chaetocerotaceae chaetoceros tortissimus', 'chromista heterokontophyta bacillariophyceae corethrales corethraceae corethron', 'chromista heterokontophyta bacillariophyceae coscinodiscales coscinodiscaceae', 'chromista heterokontophyta bacillariophyceae coscinodiscales coscinodiscaceae coscinodiscus', 'chromista heterokontophyta bacillariophyceae fragilariales fragilariaceae asterionella', 'chromista heterokontophyta bacillariophyceae fragilariales fragilariaceae asterionellopsis', 'chromista heterokontophyta bacillariophyceae fragilariales fragilariaceae asterionellopsis glacialis', 'chromista heterokontophyta bacillariophyceae fragilariales fragilariaceae ctenophora', 'chromista heterokontophyta bacillariophyceae fragilariales fragilariaceae diatoma', 'chromista heterokontophyta bacillariophyceae fragilariales fragilariaceae diatoma tenuis', 'chromista heterokontophyta bacillariophyceae fragilariales fragilariaceae fragilaria', 'chromista heterokontophyta bacillariophyceae hemiaulales hemiaulaceae cerataulina', 'chromista heterokontophyta bacillariophyceae hemiaulales hemiaulaceae cerataulina pelagica', 'chromista heterokontophyta bacillariophyceae hemiaulales hemiaulaceae climacodium', 'chromista heterokontophyta bacillariophyceae hemiaulales hemiaulaceae climacodium crocosphaera', 'chromista heterokontophyta bacillariophyceae hemiaulales hemiaulaceae eucampia', 'chromista heterokontophyta bacillariophyceae hemiaulales hemiaulaceae eucampia cornuta', 'chromista heterokontophyta bacillariophyceae hemiaulales hemiaulaceae hemiaulus', 'chromista heterokontophyta bacillariophyceae leptocylindrales leptocylindraceae leptocylindrus', 'chromista heterokontophyta bacillariophyceae leptocylindrales leptocylindraceae leptocylindrus mediterraneus', 'chromista heterokontophyta bacillariophyceae leptocylindrales leptocylindraceae tenuicylindrus belgicus', 'chromista heterokontophyta bacillariophyceae licmophorales licmophoraceae licmophora', 'chromista heterokontophyta bacillariophyceae lithodesmiales lithodesmiaceae ditylum', 'chromista heterokontophyta bacillariophyceae lithodesmiales lithodesmiaceae helicotheca tamesis', 'chromista heterokontophyta bacillariophyceae lithodesmiales lithodesmiaceae lithodesmium variabile', 'chromista heterokontophyta bacillariophyceae melosirales melosiraceae', 'chromista heterokontophyta bacillariophyceae melosirales stephanopyxidaceae stephanopyxis', 'chromista heterokontophyta bacillariophyceae naviculales naviculaceae haslea silbo', 'chromista heterokontophyta bacillariophyceae naviculales plagiotropidaceae plagiotropis', 'chromista heterokontophyta bacillariophyceae naviculales pleurosigmataceae', 'chromista heterokontophyta bacillariophyceae naviculales pleurosigmataceae pleurosigma', 'chromista heterokontophyta bacillariophyceae paraliales paraliaceae paralia', 'chromista heterokontophyta bacillariophyceae pennales', 'chromista heterokontophyta bacillariophyceae rhaponeidales rhaphoneidaceae delphineis', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae dactyliosolen', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae dactyliosolen blavyanus', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae dactyliosolen fragilissimus', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae guinardia', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae guinardia delicatula', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae guinardia flaccida', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae guinardia striata', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae pseudosolenia calcar-avis', 'chromista heterokontophyta bacillariophyceae rhizosoleniales rhizosoleniaceae rhizosolenia', 'chromista heterokontophyta bacillariophyceae thalassionematales', 'chromista heterokontophyta bacillariophyceae thalassionematales thalassionemataceae lioloma pacificum', 'chromista heterokontophyta bacillariophyceae thalassionematales thalassionemataceae thalassionema', 'chromista heterokontophyta bacillariophyceae thalassiosirales lauderiaceae lauderia', 'chromista heterokontophyta bacillariophyceae thalassiosirales lauderiaceae lauderia annulata', 'chromista heterokontophyta bacillariophyceae thalassiosirales skeletonemaceae skeletonema', 'chromista heterokontophyta bacillariophyceae thalassiosirales skeletonemaceae skeletonema menzelii', 'chromista heterokontophyta bacillariophyceae thalassiosirales thalassiosiraceae planktoniella sol', 'chromista heterokontophyta bacillariophyceae thalassiosirales thalassiosiraceae thalassiosira', 'chromista heterokontophyta bacillariophyceae thalassiosirales thalassiosiraceae thalassiosira gravida', 'chromista heterokontophyta bacillariophyceae triceratiales triceratiaceae odontella', 'chromista heterokontophyta bacillariophyceae triceratiales triceratiaceae trieres mobiliensis', 'chromista myzozoa dinophyceae', 'chromista myzozoa dinophyceae amphidiniales amphidiniaceae amphidinium', 'chromista myzozoa dinophyceae dinophyceae amphidomataceae azadinium caudatum', 'chromista myzozoa dinophyc

In [4]:
dataset_ood["train"][0]

{'image': <PIL.PngImagePlugin.PngImageFile image mode=L size=20x20>,
 'label': 54,
 'dataset': 'flowcamnet'}

In [ ]:
dataset_ood["features"]

In [ ]:
from transformers import AutoImageProcessor, AutoModelForImageClassification

model_id = "project-oceania/timm-eva02-large-m38m-ft-planktonzilla"

model = AutoModelForImageClassification.from_pretrained(model_id)

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv("planktonzilla_taxonomy_final_final.csv")

In [9]:
mask = df["proposed_label"].isna()

In [12]:
df_bad = df[mask]

df_bad = df_bad[df_bad["Dataset"] != "planktoscope"]

In [14]:
mask2 = (df["plankton"]==False)

In [15]:
df_bad2 = df[mask2]

df_bad2 = df_bad2[df_bad2["Dataset"] != "planktoscope"]

In [13]:
df_bad

,Dataset,Raw_Labels,Kingdom,Phylum,Class,Order,Family,Genus,Species,proposed_label,plankton,living
84,whoi,bad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
85,whoi,bead,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
86,whoi,bubble,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
88,whoi,detritus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
94,whoi,mix,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
744,flowcamnet,artefact,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
745,flowcamnet,detritus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
760,flowcamnet,bubble,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
770,flowcamnet,transparent_u,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
771,flowcamnet,other_living,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True

In [17]:
df_bad2[~df_bad2["proposed_label"].isna()]

,Dataset,Raw_Labels,Kingdom,Phylum,Class,Order,Family,Genus,Species,proposed_label,plankton,living
121,zoolake,fish,animalia,chordata,NaN,NaN,NaN,NaN,NaN,chordata,False,True
314,jedioceans,LClass_32.1Adult_Fish,animalia,chordata,NaN,NaN,NaN,NaN,NaN,chordata,False,True
341,jedioceans,LClass_Fish_larvae,animalia,chordata,NaN,NaN,NaN,NaN,NaN,chordata,False,True
383,jedioceans,LClass_egg,chromista,foraminifera,globothalamea,textulariida,eggerellidae,eggerella,NaN,eggerella,False,True
386,jedioceans,LClass_fish_lavae,animalia,chordata,NaN,NaN,NaN,NaN,NaN,chordata,False,True
393,jedioceans,LClass_partCrustaceo,animalia,arthropoda,NaN,NaN,NaN,NaN,NaN,arthropoda,False,False
398,jedioceans,LClass_shell,animalia,arthropoda,diplopoda,polydesmida,paradoxosomatidae,shelleyomorpha,NaN,shelleyomorpha,False,True
453,zooscan,Insecta,animalia,arthropoda,hexapoda,NaN,NaN,NaN,NaN,hexapoda,False,True
494,zooscan,other_living,animalia,arthropoda,copepoda,monstrilloida,NaN,NaN,NaN,monstrilloida,False,True
550,uvp6net,crystal,chromista,heterokontophyta,bacillariophyceae,NaN,NaN,NaN,NaN,bacillariophyceae,False,False
717,flowcamnet,light,animalia,mollusca,gastropoda,neogastropoda,fasciolariidae,lightbournus,NaN,lightbournus,False,False