In [1]:
from datasets import load_dataset

/lustre/fswork/projects/rech/tec/uod68bo/am/planktonzilla/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
dataset = load_dataset("project-oceania/planktonzilla_full")

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv("planktonzilla_taxonomy_final_final.csv")

In [9]:
mask = df["proposed_label"].isna()

In [12]:
df_bad = df[mask]

df_bad = df_bad[df_bad["Dataset"] != "planktoscope"]

In [14]:
mask2 = (df["plankton"]==False)

In [15]:
df_bad2 = df[mask2]

df_bad2 = df_bad2[df_bad2["Dataset"] != "planktoscope"]

In [13]:
df_bad

,Dataset,Raw_Labels,Kingdom,Phylum,Class,Order,Family,Genus,Species,proposed_label,plankton,living
84,whoi,bad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
85,whoi,bead,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
86,whoi,bubble,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
88,whoi,detritus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
94,whoi,mix,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
744,flowcamnet,artefact,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
745,flowcamnet,detritus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
760,flowcamnet,bubble,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
770,flowcamnet,transparent_u,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
771,flowcamnet,other_living,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True

In [17]:
df_bad2[~df_bad2["proposed_label"].isna()]

,Dataset,Raw_Labels,Kingdom,Phylum,Class,Order,Family,Genus,Species,proposed_label,plankton,living
121,zoolake,fish,animalia,chordata,NaN,NaN,NaN,NaN,NaN,chordata,False,True
314,jedioceans,LClass_32.1Adult_Fish,animalia,chordata,NaN,NaN,NaN,NaN,NaN,chordata,False,True
341,jedioceans,LClass_Fish_larvae,animalia,chordata,NaN,NaN,NaN,NaN,NaN,chordata,False,True
383,jedioceans,LClass_egg,chromista,foraminifera,globothalamea,textulariida,eggerellidae,eggerella,NaN,eggerella,False,True
386,jedioceans,LClass_fish_lavae,animalia,chordata,NaN,NaN,NaN,NaN,NaN,chordata,False,True
393,jedioceans,LClass_partCrustaceo,animalia,arthropoda,NaN,NaN,NaN,NaN,NaN,arthropoda,False,False
398,jedioceans,LClass_shell,animalia,arthropoda,diplopoda,polydesmida,paradoxosomatidae,shelleyomorpha,NaN,shelleyomorpha,False,True
453,zooscan,Insecta,animalia,arthropoda,hexapoda,NaN,NaN,NaN,NaN,hexapoda,False,True
494,zooscan,other_living,animalia,arthropoda,copepoda,monstrilloida,NaN,NaN,NaN,monstrilloida,False,True
550,uvp6net,crystal,chromista,heterokontophyta,bacillariophyceae,NaN,NaN,NaN,NaN,bacillariophyceae,False,False
717,flowcamnet,light,animalia,mollusca,gastropoda,neogastropoda,fasciolariidae,lightbournus,NaN,lightbournus,False,False